name: Build

on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

# Requires content write permission
permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Add WASM target 🔧
              run: rustup target add wasm32-unknown-unknown

            # Sync with /justfile recipe `build`
            - name: Build WASM and html 🔧
              run: |
                  cargo build --release --target wasm32-unknown-unknown &&
                  rm -rf build/ &&
                  mkdir build/ &&
                  cp target/wasm32-unknown-unknown/release/*.wasm build/ &&
                  cp assets/* build/

            # Push changes with plugin
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  # This must be the build directory
                  folder: ./build

